### ISSUE TITLE
Add option to set different properties in enviroment variable

### ISSUE THREAD

**Issue by alfredfrancis** [bitnami/bitnami-docker-solr#11]
Hi,
First of all thanks for this great docker image.

It'd be great if there is an option to customize Solr instance using environment or something. like setting jvm heap

consider following example
```
services:
  solr-node1:
    mem_limit: 4368709120
    image: bitnami/solr:latest
    environment:
      SOLR_HEAP: 4000m
```

**Comment by alfredfrancis** [comment]
also add support for Solr cloud

**Comment by alfredfrancis** [comment]
Hi,
Any update on this

**Comment by sameersbn** [comment]
You should be able to customize the java memory settings using the `JAVA_OPTS` environment variable.

```yaml
version: '2'
services:
  solr:
    image: 'bitnami/solr:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '8983:8983'
    environment:
      - JAVA_OPTS=-Xms512m -Xmx2048m -XX:PermSize=64m -XX:MaxPermSize=128m
    volumes:
      - 'solr_data:/bitnami'
volumes:
  solr_data:
    driver: local
```
