### ISSUE TITLE
docker-compose with Bitnami/Solr8 with custom core

### ISSUE THREAD

**Issue by kitestefan** [bitnami/bitnami-docker-solr#17]
Hi im trying to set up Solr 8 with docker-compose and my custom core.
It does not find my custom core that I have copied from my local folder `/solr/mycore` to `/opt/solr/server/solr/mycore` in container.

I have browsed the container `/opt/solr/server/solr/mycore` and I can see a conf dir with all my custom schemas and so on. In `/opt/solr/server/solr/mycore` I can also see my core.properties.

The server starts but can not find my core. So when I open the web gui at http://localhost:8983/solr/#/ I can only see "no cores available"
```
solr_1  | 2019-05-07 14:04:13.399 INFO  (main) [   ] o.a.s.c.CorePropertiesLocator Found 0 core definitions underneath /opt/bitnami/solr/server/solr
```

Does anyone have a clue?
```yaml
solr:
  image: bitnami/solr:8
  ports:
    - "8983:8983"
  environment:
     - SOLR_CORE_CONF_DIR=/opt/solr/server/solr/mycore
  volumes:
    - ./solr/mycore:/opt/solr/server/solr/mycore:rw
```
```
$ docker info
Containers: 9
 Running: 0
 Paused: 0
 Stopped: 9
Images: 11
Server Version: 18.09.2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 09c8266bf2fcf9519a651b04ae54c967b9ab86ec
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: linuxkit-00155d3ba51b
ID: 22ZX:S7RB:JWUQ:DRP2:GFVU:RCFA:7YOI:GOLX:T6EY:DTMZ:Q4BZ:4Z2J
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 22
 Goroutines: 47
 System Time: 2019-05-07T14:33:27.4208555Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

One important thing to mention. With Solr 7.7.1. everything works as expected.

**Comment by carrodher** [comment]
Just to confirm, in Solr 7.X are you able to import an existing core? I mean, a core no created during the first boot. According to the README, the env. variables are used to create a new core during the first run, not importing an existing one:

`SOLR_CORE`: Core name **to create at first run**. By default, it will not create a core. (E.g.: 'my_core')
`SOLR_CORE_CONF_DIR`: Configuration directory to copy **when creating a new core**

**Comment by kitestefan** [comment]
> Just to confirm, in Solr 7.X are you able to import an existing core? I mean, a core no created during the first boot. According to the README, the env. variables are used to create a new core during the first run, not importing an existing one:
> 
> `SOLR_CORE`: Core name **to create at first run**. By default, it will not create a core. (E.g.: 'my_core')
> `SOLR_CORE_CONF_DIR`: Configuration directory to copy **when creating a new core**

Thank you for your time.
In 7.7.1 my import works. My docker-compose looks like this:
  solr:
    image: solr:7.7.1
    ports:
     - "8983:8983"
    volumes:
      - ./solr/mycore:/opt/solr/server/solr/mycore:rw
It finds one core and the imported core is successfully running.

**Comment by carrodher** [comment]
I am not able to reproduce the issue, can you share with me the steps and data required to reproduce it from scratch? Thanks!

**Comment by kitestefan** [comment]
> I am not able to reproduce the issue, can you share with me the steps and data required to reproduce it from scratch? Thanks!

I have sent you the files via mail. Thanks

**Comment by carrodher** [comment]
Hi, I just tried to download it but the link expired (I saw you that mentioned the expiration date in the mail but I have not been able to check it before). Can you come alive again the link or send a new one?

**Comment by carrodher** [comment]
Hi @kitestefan, I just reproduced your issue, although I am facing it using both versions (Solr 8 and 7). I only replaced the image using the _docker-compose.yaml_ I received in the mail:
- Solr 8:
```
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
1446eb536494        bitnami/solr:8      "/app-entrypoint.sh …"   11 seconds ago      Up 10 seconds       0.0.0.0:8983->8983/tcp   solr_solr_1bash

I have no name!@1446eb536494:/$ ls -la /opt/solr/server/solr/mycore/
total 16
drwxr-xr-x 5 1001 root  160 May 23 12:39 .
drwxr-xr-x 3 root root 4096 May 23 12:50 ..
drwxr-xr-x 8 1001 root  256 May 17 13:38 conf
-rwxr-xr-x 1 1001 root  149 May 17 13:38 core.properties
```
![Screen Shot 2019-05-23 at 14 52 48](https://user-images.githubusercontent.com/13216600/58254173-77b70800-7d6a-11e9-804e-a24f23ce68ef.png)

- Solr 7:
```
$ docker ps 
CONTAINER ID        IMAGE                COMMAND                  CREATED              STATUS              PORTS                    NAMES
e5b0c2d295f7        bitnami/solr:7.7.1   "/app-entrypoint.sh …"   About a minute ago   Up About a minute   0.0.0.0:8983->8983/tcp   solr_solr_1

I have no name!@e5b0c2d295f7:/$ ls -la /opt/solr/server/solr/mycore/
total 16
drwxr-xr-x 5 1001 root  160 May 23 12:39 .
drwxr-xr-x 3 root root 4096 May 23 12:45 ..
drwxr-xr-x 8 1001 root  256 May 17 13:38 conf
-rwxr-xr-x 1 1001 root  149 May 17 13:38 core.properties
```
![Screen Shot 2019-05-23 at 14 49 21](https://user-images.githubusercontent.com/13216600/58253959-fb242980-7d69-11e9-9fa7-3ca36f433f7d.png)

___________________________________________________________________

In the same way, I was able to advance a bit more doing some changes, but at this time I am not able to have it 100% working, I need more time, but I would like to share my previous steps:

- As Solr image is non-root, you need to set the proper permissions to the mounted directory in your host:
```
sudo chown 1001:1001 ./solr/mycore
```
Non-root container images add an extra layer of security and are generally recommended for production environments. However, because they run as a non-root user, privileged tasks are typically off-limits. Learn more about non-root containers [in our docs](https://docs.bitnami.com/containers/how-to/work-with-non-root-containers/).
- You need to specify the `SOLR_CORE` env. variable; it will be used as the name for the core
```yaml
 services:
   solr:
     image: bitnami/solr:8
     environment:
       - SOLR_CORE=mycore
       - SOLR_CORE_CONF_DIR=/opt/solr/server/solr/mycore
     ports:
       - "8983:8983"
     volumes:
       - ./solr/mycore:/opt/solr/server/solr/mycore
```
- Setting above env. vars, the container should execute the following command during the initialization:
```bash
$ opt/bitnami/solr/bin/solr create_core -c mycore -d /opt/solr/server/solr/mycore -p 8983
```
where the `-c` and `-d` options come from `SOLR_CORE` and `SOLR_CORE_CONF_DIR` respectively, but it seems that this command is failing (that is what I need to investigate):
```
solr_1  | nami    INFO  Initializing solr
solr_1  | Error executing 'postInstallation': Error running: /opt/bitnami/solr/bin/solr create_core -c mycore -d /opt/solr/server/solr/mycire -p 8983
solr_1  | ERROR: Error CREATEing SolrCore 'mycore': Unable to create core [mycore] Caused by: org.apache.solr.handler.extraction.ExtractingRequestHandler
```

**Comment by msladek** [comment]
This issue might be related to #12 since I receive the following error when defining a custom config directory with 8.2.0:
```
nami    INFO  Initializing solr
Error executing 'postInstallation': Error running: /opt/bitnami/solr/bin/solr,create_core,-c,mycore,-d,solr/conf,-p,8989, {"env":{"PATH":"/opt/bitnami/java/bin:/opt/bitnami/java/bin:/opt/bitnami/solr/bin:/opt/bitnami/nami/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"},"runAs":null,"retrieveStdStreams":true}, 
```
setting `SOLR_CORE_CONF_DIR=_default` as described in the issue comment fixes the error.

**Comment by andretti1977** [comment]
I have the same problem. This is my docker-compose:
```
version: '2'

networks:
  solr-network:
    driver: bridge

services:
  solr:
    image: bitnami/solr:latest
    networks:
      - solr-network
    ports:
      - '8983:8983'
    volumes:
      - /Users/andretti/project/solr-docker/solr_data:/bitnami
      - /Users/andretti/project/solr-docker/initial-conf:/bitnami/solr/data/my_core/conf
    environment:
      - SOLR_CORE=my_core
      - SOLR_CORE_CONF_DIR=/Users/andretti/project/solr-docker/initial-conf
```

- `/Users/andretti/project/solr-docker/solr_data` is the folder i expect solr to persist new my_core data (and it works correctly when i omit SOLR_CORE_CONF_DIR env and its volume mounting)
- `/Users/andretti/project/solr-docker/initial-conf` is the folder with my custom configuration (currently just a modified version of managed-schema file) i expect docker-compose to copy after intializing my_core

When i run `docker-compose up` i get this log:

```
Creating network "solr-docker_solr-network" with driver "bridge"
Creating solr-docker_solr_1 ... done
Attaching to solr-docker_solr_1
solr_1  |
solr_1  | Welcome to the Bitnami solr container
solr_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-solr
solr_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-solr/issues
solr_1  |
solr_1  | nami    INFO  Initializing solr
solr_1  | Error executing 'postInstallation': Error running: /opt/bitnami/solr/bin/solr,create_core,-c,my_core,-d,/Users/andretti/project/solr-docker/initial-conf,-p,8983, {"env":{"PATH":"/opt/bitnami/java/bin:/opt/bitnami/java/bin:/opt/bitnami/common/bin:/opt/bitnami/solr/bin:/opt/bitnami/nami/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"},"runAs":null,"retrieveStdStreams":true},
solr-docker_solr_1 exited with code 1
```

Am i missing something?

**Comment by miguelaeh** [comment]
Hi @andretti1977 ,
The image seems to fail to create a new core.
Have in mind you are trying to mount a volume inside another volume that is also mounted. I would give it a try only mounting the one at `/bitnami`.
Apart from that, this is a non-root container so be sure that your local folders are owned by the UID `1001`.

**Comment by Chadys** [comment]
@andretti1977 
You are setting `SOLR_CORE_CONF_DIR=/Users/andretti/project/solr-docker/initial-conf` but this is a local path your container know nothing about. You should use the path you actually mounted: `SOLR_CORE_CONF_DIR=/bitnami/solr/data/my_core`.
But like @miguelaeh said, try without mount inside mount, I add some problem doing that with this image.

Unfortunately, it won't be enough to make it work, I am also getting stuck trying to use a custom conf dir.
The following docker-compose file, which is really simple and should work as per the documentation, is not using my custom configset at all:
```yaml
version: '3'
services:
  solr:
    image: bitnami/solr:8.8.0-debian-10-r10
    ports:
    - "8981:8983"
    environment:
      SOLR_CORE: custom-core
      SOLR_CORE_CONF_DIR: /custom/configsets/custom_config
    volumes:
      - solr:/bitnami/solr
      - '../solr/solr_configs_default:/custom/configsets/custom_config'
    networks:
      - solr

volumes:
  solr:

networks:
  solr:
```

Here are the logs, like you can see, no mention is made at all of my custom config:
```
Creating network "dev_solr" with the default driver
Creating volume "dev_solr" with default driver
Creating dev_solr_1 ... done
Attaching to dev_solr_1
solr_1  | solr 19:28:38.70 
solr_1  | solr 19:28:38.70 Welcome to the Bitnami solr container
solr_1  | solr 19:28:38.70 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-solr
solr_1  | solr 19:28:38.70 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-solr/issues
solr_1  | solr 19:28:38.70 
solr_1  | solr 19:28:38.70 INFO  ==> ** Starting solr setup **
solr_1  | solr 19:28:38.72 INFO  ==> Validating settings in SOLR_* env vars...
solr_1  | solr 19:28:38.72 INFO  ==> Initializing Solr ...
solr_1  | solr 19:28:38.72 INFO  ==> Configuring file permissions for Solr
solr_1  | solr 19:28:38.72 INFO  ==> Deploying Solr from scratch
solr_1  | solr 19:28:38.73 INFO  ==> Starting solr in background
solr_1  | solr 19:28:43.51 INFO  ==> Creating solr core: custom-core
solr_1  | solr 19:28:44.92 INFO  ==> Core created
solr_1  | solr 19:28:44.92 INFO  ==> Stopping solr
solr_1  | solr 19:28:45.92 INFO  ==> Persisting Solr installation
solr_1  | 
solr_1  | solr 19:28:45.97 INFO  ==> ** solr setup finished! **
solr_1  | solr 19:28:45.98 INFO  ==> ** Starting solr **
solr_1  | OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory. (error = 12)
solr_1  | OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory. (error = 12)
solr_1  | OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory. (error = 12)
solr_1  | OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory. (error = 12)
solr_1  | 2021-02-20 19:28:46.917 INFO  (main) [   ] o.e.j.u.log Logging initialized @843ms to org.eclipse.jetty.util.log.Slf4jLog
solr_1  | 2021-02-20 19:28:47.072 INFO  (main) [   ] o.e.j.s.Server jetty-9.4.34.v20201102; built: 2020-11-02T14:15:39.302Z; git: e46af88704a893fc12cb0e3bf46e2c7b48a009e7; jvm 1.8.0_282-b08
solr_1  | 2021-02-20 19:28:47.106 INFO  (main) [   ] o.e.j.d.p.ScanningAppProvider Deployment monitor [file:///opt/bitnami/solr/server/contexts/] at interval 0
solr_1  | 2021-02-20 19:28:47.384 INFO  (main) [   ] o.e.j.w.StandardDescriptorProcessor NO JSP Support for /solr, did not find org.apache.jasper.servlet.JspServlet
solr_1  | 2021-02-20 19:28:47.394 INFO  (main) [   ] o.e.j.s.session DefaultSessionIdManager workerName=node0
solr_1  | 2021-02-20 19:28:47.395 INFO  (main) [   ] o.e.j.s.session No SessionScavenger set, using defaults
solr_1  | 2021-02-20 19:28:47.397 INFO  (main) [   ] o.e.j.s.session node0 Scavenging every 600000ms
solr_1  | 2021-02-20 19:28:47.468 INFO  (main) [   ] o.a.s.s.SolrDispatchFilter Using logger factory org.apache.logging.slf4j.Log4jLoggerFactory
solr_1  | 2021-02-20 19:28:47.473 INFO  (main) [   ] o.a.s.s.SolrDispatchFilter  ___      _       Welcome to Apache Solr? version 8.8.0
solr_1  | 2021-02-20 19:28:47.473 INFO  (main) [   ] o.a.s.s.SolrDispatchFilter / __| ___| |_ _   Starting in standalone mode on port 8983
solr_1  | 2021-02-20 19:28:47.473 INFO  (main) [   ] o.a.s.s.SolrDispatchFilter \__ \/ _ \ | '_|  Install dir: /opt/bitnami/solr
solr_1  | 2021-02-20 19:28:47.473 INFO  (main) [   ] o.a.s.s.SolrDispatchFilter |___/\___/_|_|    Start time: 2021-02-20T19:28:47.473Z
solr_1  | 2021-02-20 19:28:47.478 INFO  (main) [   ] o.a.s.c.SolrPaths Using system property solr.solr.home: /opt/bitnami/solr/server/solr
solr_1  | 2021-02-20 19:28:47.479 INFO  (main) [   ] o.a.s.c.SolrXmlConfig Loading container configuration from /opt/bitnami/solr/server/solr/solr.xml
solr_1  | 2021-02-20 19:28:47.659 INFO  (main) [   ] o.a.s.c.SolrXmlConfig MBean server found: com.sun.jmx.mbeanserver.JmxMBeanServer@12b0404f, but no JMX reporters were configured - adding default JMX reporter.
solr_1  | 2021-02-20 19:28:48.087 INFO  (main) [   ] o.a.s.h.c.HttpShardHandlerFactory Host whitelist initialized: WhitelistHostChecker [whitelistHosts=null, whitelistHostCheckingEnabled=true]
solr_1  | 2021-02-20 19:28:48.229 WARN  (main) [   ] o.e.j.u.s.S.config Trusting all certificates configured for Client@5357c287[provider=null,keyStore=null,trustStore=null]
solr_1  | 2021-02-20 19:28:48.229 WARN  (main) [   ] o.e.j.u.s.S.config No Client EndPointIdentificationAlgorithm configured for Client@5357c287[provider=null,keyStore=null,trustStore=null]
solr_1  | 2021-02-20 19:28:48.351 WARN  (main) [   ] o.e.j.u.s.S.config Trusting all certificates configured for Client@5df417a7[provider=null,keyStore=null,trustStore=null]
solr_1  | 2021-02-20 19:28:48.351 WARN  (main) [   ] o.e.j.u.s.S.config No Client EndPointIdentificationAlgorithm configured for Client@5df417a7[provider=null,keyStore=null,trustStore=null]
solr_1  | 2021-02-20 19:28:48.398 WARN  (main) [   ] o.a.s.c.CoreContainer Not all security plugins configured!  authentication=disabled authorization=disabled.  Solr is only as secure as you make it. Consider configuring authentication/authorization before exposing Solr to users internal or external.  See https://s.apache.org/solrsecurity for more info
solr_1  | 2021-02-20 19:28:48.527 INFO  (main) [   ] o.a.s.c.TransientSolrCoreCacheDefault Allocating transient cache for 2147483647 transient cores
solr_1  | 2021-02-20 19:28:48.529 INFO  (main) [   ] o.a.s.h.a.MetricsHistoryHandler No .system core, keeping metrics history in memory.
solr_1  | 2021-02-20 19:28:48.602 INFO  (main) [   ] o.a.s.m.r.SolrJmxReporter JMX monitoring for 'solr.node' (registry 'solr.node') enabled at server: com.sun.jmx.mbeanserver.JmxMBeanServer@12b0404f
solr_1  | 2021-02-20 19:28:48.603 INFO  (main) [   ] o.a.s.m.r.SolrJmxReporter JMX monitoring for 'solr.jvm' (registry 'solr.jvm') enabled at server: com.sun.jmx.mbeanserver.JmxMBeanServer@12b0404f
solr_1  | 2021-02-20 19:28:48.608 INFO  (main) [   ] o.a.s.m.r.SolrJmxReporter JMX monitoring for 'solr.jetty' (registry 'solr.jetty') enabled at server: com.sun.jmx.mbeanserver.JmxMBeanServer@12b0404f
solr_1  | 2021-02-20 19:28:48.645 INFO  (main) [   ] o.a.s.c.CorePropertiesLocator Found 1 core definitions underneath /opt/bitnami/solr/server/solr
solr_1  | 2021-02-20 19:28:48.646 INFO  (main) [   ] o.a.s.c.CorePropertiesLocator Cores are: [custom-core]
solr_1  | 2021-02-20 19:28:48.685 INFO  (coreLoadExecutor-13-thread-1) [   x:custom-core] o.a.s.c.SolrConfig Using Lucene MatchVersion: 8.8.0
solr_1  | 2021-02-20 19:28:48.723 INFO  (main) [   ] o.e.j.s.h.ContextHandler Started o.e.j.w.WebAppContext@13e344d{/solr,file:///opt/bitnami/solr/server/solr-webapp/webapp/,AVAILABLE}{/opt/bitnami/solr/server/solr-webapp/webapp}
solr_1  | 2021-02-20 19:28:48.745 INFO  (main) [   ] o.e.j.s.AbstractConnector Started ServerConnector@865dd6{HTTP/1.1, (http/1.1, h2c)}{0.0.0.0:8983}
solr_1  | 2021-02-20 19:28:48.745 INFO  (main) [   ] o.e.j.s.Server Started @2672ms
solr_1  | 2021-02-20 19:28:48.852 INFO  (coreLoadExecutor-13-thread-1) [   x:custom-core] o.a.s.s.IndexSchema Schema name=default-config
solr_1  | 2021-02-20 19:28:49.348 INFO  (coreLoadExecutor-13-thread-1) [   x:custom-core] o.a.s.s.IndexSchema Loaded schema default-config/1.6 with uniqueid field id
solr_1  | 2021-02-20 19:28:49.395 INFO  (coreLoadExecutor-13-thread-1) [   x:custom-core] o.a.s.c.CoreContainer Creating SolrCore 'custom-core' using configuration from instancedir /opt/bitnami/solr/server/solr/custom-core, trusted=true
solr_1  | 2021-02-20 19:28:49.442 INFO  (coreLoadExecutor-13-thread-1) [   x:custom-core] o.a.s.m.r.SolrJmxReporter JMX monitoring for 'solr.core.custom-core' (registry 'solr.core.custom-core') enabled at server: com.sun.jmx.mbeanserver.JmxMBeanServer@12b0404f
solr_1  | 2021-02-20 19:28:49.457 INFO  (coreLoadExecutor-13-thread-1) [   x:custom-core] o.a.s.c.SolrCore [[custom-core] ] Opening new SolrCore at [/opt/bitnami/solr/server/solr/custom-core], dataDir=[/opt/bitnami/solr/server/solr/custom-core/data/]
solr_1  | 2021-02-20 19:28:49.908 INFO  (coreLoadExecutor-13-thread-1) [   x:custom-core] o.a.s.u.UpdateHandler Using UpdateLog implementation: org.apache.solr.update.UpdateLog
solr_1  | 2021-02-20 19:28:49.908 INFO  (coreLoadExecutor-13-thread-1) [   x:custom-core] o.a.s.u.UpdateLog Initializing UpdateLog: dataDir= defaultSyncLevel=FLUSH numRecordsToKeep=100 maxNumLogsToKeep=10 numVersionBuckets=65536
solr_1  | 2021-02-20 19:28:49.925 INFO  (coreLoadExecutor-13-thread-1) [   x:custom-core] o.a.s.u.CommitTracker Hard AutoCommit: if uncommitted for 15000ms; 
solr_1  | 2021-02-20 19:28:49.925 INFO  (coreLoadExecutor-13-thread-1) [   x:custom-core] o.a.s.u.CommitTracker Soft AutoCommit: disabled
solr_1  | 2021-02-20 19:28:50.059 INFO  (coreLoadExecutor-13-thread-1) [   x:custom-core] o.a.s.r.ManagedResourceStorage File-based storage initialized to use dir: /opt/bitnami/solr/server/solr/custom-core/conf
solr_1  | 2021-02-20 19:28:50.071 INFO  (coreLoadExecutor-13-thread-1) [   x:custom-core] o.a.s.h.c.SpellCheckComponent Initializing spell checkers
solr_1  | 2021-02-20 19:28:50.076 INFO  (coreLoadExecutor-13-thread-1) [   x:custom-core] o.a.s.s.DirectSolrSpellChecker init: {name=default,field=_text_,classname=solr.DirectSolrSpellChecker,distanceMeasure=internal,accuracy=0.5,maxEdits=2,minPrefix=1,maxInspections=5,minQueryLength=4,maxQueryFrequency=0.01}
solr_1  | 2021-02-20 19:28:50.084 INFO  (coreLoadExecutor-13-thread-1) [   x:custom-core] o.a.s.h.ReplicationHandler Commits will be reserved for 10000 ms
solr_1  | 2021-02-20 19:28:50.091 INFO  (coreLoadExecutor-13-thread-1) [   x:custom-core] o.a.s.u.UpdateLog Could not find max version in index or recent updates, using new clock 1692243675149500416
solr_1  | 2021-02-20 19:28:50.096 INFO  (searcherExecutor-15-thread-1-processing-x:custom-core) [   x:custom-core] o.a.s.c.QuerySenderListener QuerySenderListener done.
solr_1  | 2021-02-20 19:28:50.097 INFO  (searcherExecutor-15-thread-1-processing-x:custom-core) [   x:custom-core] o.a.s.h.c.SpellCheckComponent Loading spell index for spellchecker: default
solr_1  | 2021-02-20 19:28:50.129 INFO  (searcherExecutor-15-thread-1-processing-x:custom-core) [   x:custom-core] o.a.s.c.SolrCore [custom-core]  Registered new searcher autowarm time: 0 ms
solr_1  | 2021-02-20 19:29:05.347 INFO  (qtp1922464006-16) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/cores params={indexInfo=false&wt=json&_=1613849345300} status=0 QTime=6
solr_1  | 2021-02-20 19:29:05.356 INFO  (qtp1922464006-42) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/info/system params={wt=json&_=1613849345300} status=0 QTime=15
solr_1  | 2021-02-20 19:29:10.199 INFO  (qtp1922464006-42) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/cores params={indexInfo=false&wt=json&_=1613849345300} status=0 QTime=0
solr_1  | 2021-02-20 19:29:10.203 INFO  (qtp1922464006-39) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/info/system params={wt=json&_=1613849345300} status=0 QTime=5
solr_1  | 2021-02-20 19:29:10.214 INFO  (qtp1922464006-18) [   x:custom-core] o.a.s.c.S.Request [custom-core]  webapp=/solr path=/admin/ping params={action=status&wt=json&_=1613849345300&ts=1613849345300} status=503 QTime=8
solr_1  | 2021-02-20 19:29:10.216 INFO  (qtp1922464006-15) [   x:custom-core] o.a.s.c.S.Request [custom-core]  webapp=/solr path=/replication params={wt=json&command=details&_=1613849350189} status=0 QTime=10
solr_1  | 2021-02-20 19:29:10.231 INFO  (qtp1922464006-24) [   x:custom-core] o.a.s.c.S.Request [custom-core]  webapp=/solr path=/admin/luke params={numTerms=0&show=index&wt=json&_=1613849350188} status=0 QTime=25
solr_1  | 2021-02-20 19:29:10.233 INFO  (qtp1922464006-42) [   x:custom-core] o.a.s.c.S.Request [custom-core]  webapp=/solr path=/admin/system params={wt=json&_=1613849350189} status=0 QTime=18
solr_1  | 2021-02-20 19:29:14.259 INFO  (qtp1922464006-39) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/cores params={indexInfo=false&wt=json&_=1613849345300} status=0 QTime=0
solr_1  | 2021-02-20 19:29:14.265 INFO  (qtp1922464006-42) [   ] o.a.s.s.HttpSolrCall [admin] webapp=null path=/admin/info/system params={wt=json&_=1613849345300} status=0 QTime=5
solr_1  | 2021-02-20 19:29:14.268 INFO  (qtp1922464006-21) [   x:custom-core] o.a.s.c.S.Request [custom-core]  webapp=/solr path=/admin/file params={wt=json&_=1613849345333} status=0 QTime=0
solr_1  | 2021-02-20 19:29:14.285 INFO  (qtp1922464006-24) [   x:custom-core] o.a.s.c.S.Request [custom-core]  webapp=/solr path=/admin/file params={file=lang&wt=json&_=1613849345333} status=0 QTime=1
```
My local folder is owned by UID 1001:
```shell
ls -l ../solr/                    
total 0
drwxr-xr-x  3 1001    1001   96 20 Feb 17:46 solr_configs_default
```
The conf of my new core keep using `_default` no matter what.

I also tried it with cloud mode and a zookeeper cluster, without expecting much, and no surprise, it won't work either. There should be an easy, documented (and actually working) way to change the default configset used when creating core, whether in cloud or non-cloud configuration. For cloud, using `bootstrap_confdir` and `collection.configName` in solr instanciation would probably be useful. I also tried to make it work by directly overriding `_default` configset but got all kind of permission errors (actually, I tried a LOT OF different solution, without much success).

For people getting stuck like me, here are the solution I ended up with, for now:
- For a non-cloud configuration, simply use the solr official image (and not the bitnami one) like this (I didn't add persistence, don't forget to do it):
```yaml
version: '3'
services:
  solr:
    image: solr:8.8.0-slim
    ports:
      - "8981:8983"
    entrypoint: solr-precreate custom-core /opt/solr/server/solr/configsets/custom_config
    volumes:
      - '<path_to_custom_configset_containing_conf_folder>:/opt/solr/server/solr/configsets/custom_config:ro'
    networks:
      - solr
```
- For cloud configuration, for now I don't have a solution that doesn't need you to launch a command on the container after creation. Here is my docker-compose.yml:
```yaml
x-solr_envs: &solr_envs
  SOLR_ZK_HOSTS: zoo1:2181,zoo2:2181,zoo3:2181
  SOLR_ENABLE_CLOUD_MODE: "yes"
  SOLR_NUMBER_OF_NODES: 3
  SOLR_COLLECTION_SHARDS: 1
  SOLR_COLLECTION_REPLICAS: 3
  SOLR_CORE_CONF_DIR: /custom/configsets/custom_config  # this won't actually be used by the image, but will be needed by the custom script

x-zookeeper_envs: &zookeeper_envs
  ZOO_4LW_COMMANDS_WHITELIST: srvr,mntr,conf,ruok
  ALLOW_ANONYMOUS_LOGIN: "yes"
  ZOO_SERVERS: zoo1:2888:3888 zoo2:2888:3888 zoo3:2888:3888


version: '3'
services:
  solr1:
    image: bitnami/solr:8.8.0-debian-10-r10
    ports:
    - "8981:8983"
    environment:
      <<: *solr_envs
      SOLR_HOST: solr1
      SOLR_CLOUD_BOOTSTRAP: "yes"
      SOLR_COLLECTION: collection
    volumes:
      - solr1:/bitnami/solr
      - '<path_to_custom_configset_containing_conf_folder>:/custom/configsets/custom_config'
      - '<path_to_script>:/custom/scripts/load_dommarket_configset.sh'
    networks:
      - solr
    depends_on:
      - zoo1
      - zoo2
      - zoo3
#
  solr2:
    image: bitnami/solr:8.8.0-debian-10-r10
#    ports:
#      - "8982:8983"
    environment:
      <<: *solr_envs
      SOLR_HOST: solr2
    volumes:
      - solr2:/bitnami/solr
    networks:
      - solr
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  solr3:
    image: bitnami/solr:8.8.0-debian-10-r10
#    ports:
#      - "8983:8983"
    environment:
      <<: *solr_envs
      SOLR_HOST: solr3
    volumes:
      - solr3:/bitnami/solr
    networks:
      - solr
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  zoo1:
    image: bitnami/zookeeper:3.6.2-debian-10-r124
#    ports:
#      - 2181:2181
#      - 7001:7000
    environment:
      ZOO_SERVER_ID: 1
      <<: *zookeeper_envs
    networks:
      - solr
    volumes:
      - zoo1:/bitnami/zookeeper

  zoo2:
    image: bitnami/zookeeper:3.6.2-debian-10-r124
#    ports:
#      - 2182:2181
#      - 7002:7000
    environment:
      ZOO_SERVER_ID: 2
      <<: *zookeeper_envs
    networks:
      - solr
    volumes:
      - zoo2:/bitnami/zookeeper

  zoo3:
    image: bitnami/zookeeper:3.6.2-debian-10-r124
#    ports:
#      - 2183:2181
#      - 7003:7000
    environment:
      ZOO_SERVER_ID: 3
      <<: *zookeeper_envs
    networks:
      - solr
    volumes:
      - zoo3:/bitnami/zookeeper

networks:
  solr:

volumes:
  solr1:
  solr2:
  solr3:
  zoo1:
  zoo2:
  zoo3:
```
And after running your container, simply do:
```shell
docker-compose exec solr1 /custom/scripts/load_dommarket_configset.sh
```
And for the script, put the following inside it:
```shell
#!/bin/sh

solr zk -upconfig -n ${SOLR_COLLECTION} -z "${SOLR_ZK_HOSTS}/solr" -d ${SOLR_CORE_CONF_DIR}/conf &&
curl "http://localhost:${SOLR_PORT_NUMBER}/solr/admin/collections?action=RELOAD&name=${SOLR_COLLECTION}"  # add this if you use auth --user "${SOLR_ADMIN_USERNAME}:${SOLR_ADMIN_PASSWORD}"
```
PS: knowing to add "/solr" after `SOLR_ZK_HOSTS` actually cost me so much time, better documentation about this solr image automatically doing a chroot on the zookeeper would be appreciated also
